//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pear.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Advertisements = new HashSet<Advertisement>();
            this.MerchantReviews = new HashSet<MerchantReview>();
        }
    
        public int MerchantId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Name { get; set; }
        public string LogoUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        public virtual ICollection<MerchantReview> MerchantReviews { get; set; }
    }
}
